export interface UbsiCampus {
  id: string
  name: string
  address: string
  city: string
  province: string
  postal_code?: string
  phone?: string
  lat?: number
  lng?: number
}

export const UBSI_CAMPUSES: UbsiCampus[] = [
  {
    id: 'kramat-98',
    name: 'UBSI Kampus Kramat 98 (Pusat / Rektorat)',
    address: 'Jl. Kramat Raya No.98, RT.2/RW.9, Kwitang, Kec. Senen',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    postal_code: '10420',
    lat: -6.1852,
    lng: 106.8427,
  },
  {
    id: 'salemba-22',
    name: 'UBSI Kampus Salemba 22',
    address: 'Jl. Salemba Raya No.22, RT.3/RW.6, Kenari, Kec. Senen',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    postal_code: '10430',
    lat: -6.1916,
    lng: 106.8488,
  },
  {
    id: 'salemba-45',
    name: 'UBSI Kampus Salemba 45',
    address: 'Jl. Salemba Raya No.45, RT.4/RW.5, Paseban, Kec. Senen',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    postal_code: '10440',
    lat: -6.1963,
    lng: 106.8517,
  },
  {
    id: 'pemuda',
    name: 'UBSI Kampus Pemuda',
    address: 'Jl. Kayu Jati 5 No.2, RT.8/RW.4, Rawamangun, Kec. Pulo Gadung',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    postal_code: '13220',
    lat: -6.1947,
    lng: 106.8879,
  },
  {
    id: 'dewi-sartika',
    name: 'UBSI Kampus Dewi Sartika',
    address: 'Jl. Dewi Sartika No.289, RT.4/RW.5, Cawang, Kec. Kramat Jati',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    postal_code: '13630',
    lat: -6.2573,
    lng: 106.8647,
  },
  {
    id: 'jatiwaringin',
    name: 'UBSI Kampus Jatiwaringin',
    address: 'Jl. Raya Jatiwaringin No.18, RT.3/RW.8, Pondok Gede',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    postal_code: '17411',
    lat: -6.2694,
    lng: 106.9114,
  },
  {
    id: 'cengkareng',
    name: 'UBSI Kampus Cengkareng',
    address: 'Jl. Raya Kamal No.20, RT.6/RW.2, Cengkareng Barat',
    city: 'Jakarta Barat',
    province: 'DKI Jakarta',
    postal_code: '11730',
    lat: -6.1432,
    lng: 106.7268,
  },
  {
    id: 'slipi',
    name: 'UBSI Kampus Slipi / Kemanggisan',
    address: 'Jl. Kemanggisan Utama Raya No.3, RT.1/RW.7, Slipi, Palmerah',
    city: 'Jakarta Barat',
    province: 'DKI Jakarta',
    postal_code: '11480',
    lat: -6.1952,
    lng: 106.7924,
  },
  {
    id: 'fatmawati',
    name: 'UBSI Kampus Fatmawati',
    address: 'Jl. RS. Fatmawati Raya No.24, RT.1/RW.10, Pondok Labu, Cilandak',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postal_code: '12450',
    lat: -6.3021,
    lng: 106.7972,
  },
  {
    id: 'warung-buncit',
    name: 'UBSI Kampus Warung Buncit',
    address: 'Jl. Warung Buncit Raya No.25, RT.1/RW.7, Kalibata, Pancoran',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postal_code: '12740',
    lat: -6.2625,
    lng: 106.8298,
  },
  {
    id: 'margonda',
    name: 'UBSI Kampus Margonda (Depok)',
    address: 'Jl. Margonda Raya No.8, Pondok Cina, Kec. Beji',
    city: 'Kota Depok',
    province: 'Jawa Barat',
    postal_code: '16424',
    lat: -6.3721,
    lng: 106.8322,
  },
  {
    id: 'bsd',
    name: 'UBSI Kampus BSD / Serpong',
    address: 'Jl. Raya Serpong BSD Sektor XIV Blok C1/1, Rawa Mekar Jaya, Serpong',
    city: 'Kota Tangerang Selatan',
    province: 'Banten',
    postal_code: '15310',
    lat: -6.3094,
    lng: 106.6853,
  },
  {
    id: 'ciputat',
    name: 'UBSI Kampus Ciputat',
    address: 'Jl. Ir. H. Juanda No.39, Pisangan, Ciputat Timur',
    city: 'Kota Tangerang Selatan',
    province: 'Banten',
    postal_code: '15419',
    lat: -6.3142,
    lng: 106.7533,
  },
  {
    id: 'cimone',
    name: 'UBSI Kampus Cimone (Tangerang)',
    address: 'Jl. Raya Gatot Subroto No.8, RT.001/RW.002, Cimone, Kec. Karawaci',
    city: 'Kota Tangerang',
    province: 'Banten',
    postal_code: '15114',
    lat: -6.1968,
    lng: 106.6084,
  },
  {
    id: 'ciledug',
    name: 'UBSI Kampus Ciledug',
    address: 'Jl. Raden Fatah No.19, Sudimara Barat, Kec. Ciledug',
    city: 'Kota Tangerang',
    province: 'Banten',
    postal_code: '15151',
    lat: -6.2291,
    lng: 106.7118,
  },
  {
    id: 'cut-mutia',
    name: 'UBSI Kampus Cut Mutia (Bekasi)',
    address: 'Jl. Cut Mutia No.88, Sepanjang Jaya, Kec. Rawalumbu',
    city: 'Kota Bekasi',
    province: 'Jawa Barat',
    postal_code: '17114',
    lat: -6.2608,
    lng: 106.9972,
  },
  {
    id: 'kaliabang',
    name: 'UBSI Kampus Kaliabang (Bekasi)',
    address: 'Jl. Kaliabang Jaya No.1, Harapan Jaya, Kec. Bekasi Utara',
    city: 'Kota Bekasi',
    province: 'Jawa Barat',
    postal_code: '17124',
    lat: -6.2087,
    lng: 107.0135,
  },
  {
    id: 'cikarang',
    name: 'UBSI Kampus Cikarang',
    address: 'Jl. Raya Cikarang Cibarusah No.168, Pasirsari, Cikarang Selatan',
    city: 'Kabupaten Bekasi',
    province: 'Jawa Barat',
    postal_code: '17530',
    lat: -6.3142,
    lng: 107.1428,
  },
  {
    id: 'karawang',
    name: 'UBSI Kampus Karawang',
    address: 'Jl. Banten No.1, Karangpawitan, Kec. Karawang Barat',
    city: 'Kabupaten Karawang',
    province: 'Jawa Barat',
    postal_code: '41315',
    lat: -6.3045,
    lng: 107.3021,
  },
  {
    id: 'cikampek',
    name: 'UBSI Kampus Cikampek',
    address: 'Jl. Ir. H. Juanda No.17, Dawuan Barat, Kec. Cikampek',
    city: 'Kabupaten Karawang',
    province: 'Jawa Barat',
    postal_code: '41373',
    lat: -6.4172,
    lng: 107.4568,
  },
  {
    id: 'sukabumi',
    name: 'UBSI Kampus Sukabumi',
    address: 'Jl. Cemerlang No.8, Sukakarya, Kec. Warudoyong',
    city: 'Kota Sukabumi',
    province: 'Jawa Barat',
    postal_code: '43135',
    lat: -6.9248,
    lng: 106.9142,
  },
  {
    id: 'tasikmalaya',
    name: 'UBSI Kampus Tasikmalaya',
    address: 'Jl. Tanuwijaya No.4, Empangsari, Kec. Tawang',
    city: 'Kota Tasikmalaya',
    province: 'Jawa Barat',
    postal_code: '46113',
    lat: -7.3278,
    lng: 108.2215,
  },
  {
    id: 'tegal',
    name: 'UBSI Kampus Tegal',
    address: 'Jl. Sipelem No.22, Kraton, Kec. Tegal Barat',
    city: 'Kota Tegal',
    province: 'Jawa Tengah',
    postal_code: '52112',
    lat: -6.8682,
    lng: 109.1235,
  },
  {
    id: 'purwokerto',
    name: 'UBSI Kampus Purwokerto',
    address: 'Jl. HR. Bunyamin No.106, Pabuaran, Kec. Purwokerto Utara',
    city: 'Kabupaten Banyumas',
    province: 'Jawa Tengah',
    postal_code: '53124',
    lat: -7.4021,
    lng: 109.2458,
  },
  {
    id: 'surakarta',
    name: 'UBSI Kampus Surakarta (Solo)',
    address: 'Jl. Letjen Sutoyo No.43, Mojosongo, Kec. Jebres',
    city: 'Kota Surakarta',
    province: 'Jawa Tengah',
    postal_code: '57127',
    lat: -7.5458,
    lng: 110.8421,
  },
  {
    id: 'yogyakarta',
    name: 'UBSI Kampus Yogyakarta',
    address: 'Jl. Ringroad Barat, Ambarketawang, Kec. Gamping',
    city: 'Kabupaten Sleman',
    province: 'D.I. Yogyakarta',
    postal_code: '55294',
    lat: -7.7985,
    lng: 110.3242,
  },
  {
    id: 'pontianak',
    name: 'UBSI Kampus Pontianak',
    address: 'Jl. Abdurrahman Saleh No.18A, Bangka Belitung Laut, Kec. Pontianak Tenggara',
    city: 'Kota Pontianak',
    province: 'Kalimantan Barat',
    postal_code: '78124',
    lat: -0.0521,
    lng: 109.3458,
  },
]

export function getUbsiCampusById(id: string): UbsiCampus | undefined {
  return UBSI_CAMPUSES.find(c => c.id === id)
}

export function searchUbsiCampuses(query: string): UbsiCampus[] {
  if (!query || !query.trim()) return UBSI_CAMPUSES
  const q = query.toLowerCase().trim()
  return UBSI_CAMPUSES.filter(
    c =>
      c.name.toLowerCase().includes(q) ||
      c.city.toLowerCase().includes(q) ||
      c.province.toLowerCase().includes(q) ||
      c.address.toLowerCase().includes(q)
  )
}
