import {
  Boxes,
  ChartNoAxesCombined,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CreditCard,
  GalleryHorizontalEnd,
  LayoutDashboard,
  LogOut,
  Megaphone,
  Menu,
  MessagesSquare,
  Moon,
  Package,
  Search,
  Settings,
  Shapes,
  ShoppingBag,
  Star,
  Sun,
  Truck,
  UserRound,
  Users,
  UserRoundX,
  X,
  Check,
  Plus,
  Pencil,
  Trash2,
  RefreshCw,
  MoreHorizontal,
  AlertTriangle,
  Eye,
  EyeOff,
  Save,
  Database,
  Bell,
  Wifi,
  ArrowUpRight,
  Sparkles,
  Ruler,
  BadgeDollarSign,
  Images,
  Palette,
  Upload,
  CheckCircle2,
  Tag,
  TrendingUp,
  ShoppingCart,
  MessageSquare,
  MessageCircle,
  Power,
  ChevronDown,
  User,
  Image as ImageIcon,
  Filter,
  FileText,
  Download,
  ArrowDown,
  ArrowUp,
  BarChart3,
  Printer,
  ExternalLink,
  Receipt,
  Send,
  SendHorizontal,
  Clock,
} from "lucide-react";
import type { LucideProps } from "lucide-react";

const icons = {
  Boxes, ChartNoAxesCombined, ChevronLeft, ChevronRight, CircleHelp, CreditCard,
  GalleryHorizontalEnd, LayoutDashboard, LogOut, Megaphone, Menu, MessagesSquare,
  Moon, Package, Search, Settings, Shapes, ShoppingBag, Star, Sun, Truck, UserRound,
  Users, UserRoundX, X, Check, Plus, Pencil, Trash2, RefreshCw, MoreHorizontal, AlertTriangle,
  Eye, EyeOff, Save, Database, Bell, Wifi, ArrowUpRight, Sparkles, Ruler, BadgeDollarSign,
  Images, Palette, Upload, CheckCircle2, Tag, TrendingUp, ShoppingCart, MessageSquare,
  MessageCircle, Power, ChevronDown, User, Image: ImageIcon, Filter,
  FileText, Download, ArrowDown, ArrowUp, BarChart3, Printer, ExternalLink, Receipt,
  Send, SendHorizontal, Clock,
};

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: LucideProps & { name: string }) {
  const Component = icons[name as IconName] || CircleHelp;
  return <Component aria-hidden="true" {...props} />;
}

